spring:
  datasource:
    url: jdbc:h2:mem:studentdb
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

